### ISSUE TITLE
The documentation for distributed_backend is incorrect, it should be renamed 'accelelator' in recent pl version

### ISSUE THREAD

**Issue by bw4sz** [weecology/DeepForest#342]
```
ValueError: You selected an invalid accelerator name: `accelerator='ddp'`. Available names are: cpu, cuda, hpu, ipu, mps, tpu.
```
```
# Config file for DeepForest pytorch module

#cpu workers for data loaders
#Dataloaders
workers: 12
gpus: 2
distributed_backend: ddp
batch_size: 8

#Non-max supression of overlapping predictions
nms_thresh: 0.05
score_thresh: 0.3

train:

    csv_file:
    root_dir:

    #Optomizer  initial learning rate
    lr: 0.001

    #Print loss every n epochs
    epochs: 62
    #Useful debugging flag in pytorch lightning, set to True to get a single batch of training to test settings.
    fast_dev_run: False

    #pin images to GPU memory for fast training. This depends on GPU size and number of images.
    preload_images: True

validation:
    #callback args
    csv_file:
    root_dir:
    #Intersection over union evaluation
    iou_threshold: 0.4
    val_accuracy_interval: 1
```

This was changed in a major release for pytorch lightning. The docs are now outdated.

https://deepforest.readthedocs.io/en/latest/ConfigurationFile.html#distributed-backend
